spring:
  datasource:
    url : jdbc:mysql://localhost:3306/bookstore1?serverTimezone=GMT%2B8
    username : root
    password : 123456
    driverClassName : com.mysql.cj.jdbc.Driver
  jpa:
    database : MYSQL
    show-sql : true
    hibernate:
      ddl-auto : update
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: comments


